### ISSUE TITLE
Wrong redirect link

### ISSUE THREAD

**Issue by vichi99** [flaiming/simple-wishlist#11]
Just created link http://wishlist.oram.cz/2ff65691/ is redirecting to the empty list https://sdilejprani.cz/

**Comment by flaiming** [comment]
Hi, probably wrong nginx redirect, will fix ASAP.

**Comment by flaiming** [comment]
It is fixed now, thanks for reporting it. 
I actually didn't know that it is still being used by someone outside me and my family :)
